// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxluxdlteqsmmwcyziwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bHV4ZGx0ZXFzbW13Y3l6aXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDQ3NzMsImV4cCI6MjA2OTIyMDc3M30.s1DLpx-HI4u09IwegSxIx2xv2g9iUUfKVIqU2sJ4YmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});